version: '2.3'

# This block is used for inclusion in the environment section of each container.
x-volumes:
  &extended-volumes
    volumes:
      - 'projectroot:/app'
      - 'design-system:/deps/design-system/'
      - 'react:/deps/react/'

services:
  php:
    <<: [*extended-volumes]
  cli:
    <<: [*extended-volumes]
  nginx:
    <<: [*extended-volumes]

volumes:
  projectroot:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}
      o: bind
  design-system:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/../design-system/
      o: bind
  react:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/../react/
      o: bind
